### ISSUE TITLE
Add Autoupdate of Content Index

### ISSUE THREAD

**Issue by kristianserrano** [emory-libraries/templating-engine#48]
Currently, allowing new content to display requires a manual update of the index.

We need to automatically update new, changed, or deleted content. ~~either when content has been published or unpublished from Cascade using fswatch, or we check and update the index when a URL is accessed.~~

**Comment by laurenhamel** [comment]
I just want to add that I am a bit hesitant to go the route of updating the index when a URL is accessed because, then, we're somewhat resorting back to running that indexing process before rendering, which we know negatively impacts the page load time. I also foresee it being difficult to identify exactly when the re-indexing should be triggered. Ideally, we can keep these two processes entirely separate.

**Comment by laurenhamel** [comment]
@kristianserrano, I'm wondering if this should be an epic? Related to this is #30 and #31, which if we take that approach, it'll likely result in a number of other related issues we'll need to identify and add in here in terms of configuration, setup, deployment, etc.

**Comment by kristianserrano** [comment]
Agreed. I'm not a fan of that either. I probably shouldn't prescribe possible solutions in general and just state the problem.

And yes, I'll make it an epic

**Comment by kristianserrano** [comment]
Moving this into blocked until James has set up what we need and we've tested successfully.

**Comment by libdgg** [comment]
@kristianserrano @laurenhamel per our standup decision on 5/30 to implement the manual trigger I'm moving this issue to Sprint 15 to revisit this topic and a long term solution at a later date.

**Comment by laurenhamel** [comment]
This is no longer relevant as the templating engine is being decommissioned for Phase 2.
